// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkijltcowhhxdhixnvba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1raWpsdGNvd2hoeGRoaXhudmJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTA4NDYsImV4cCI6MjA2NDM2Njg0Nn0.kO-QVPrD3BnRp-voyFtJusVbqELS6nBY6Q9XrMVAkJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);